version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db:/data/postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  db:
    driver: local